// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: Message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SET_GAME_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId          uint32   `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	IsReconnect     bool     `protobuf:"varint,2,opt,name=IsReconnect,proto3" json:"IsReconnect,omitempty"`
	IsRestore       bool     `protobuf:"varint,3,opt,name=IsRestore,proto3" json:"IsRestore,omitempty"`
	IsBanBootEntity bool     `protobuf:"varint,4,opt,name=IsBanBootEntity,proto3" json:"IsBanBootEntity,omitempty"`
	EntityIdList    []string `protobuf:"bytes,5,rep,name=EntityIdList,proto3" json:"EntityIdList,omitempty"`
}

func (x *SET_GAME_ID) Reset() {
	*x = SET_GAME_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SET_GAME_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SET_GAME_ID) ProtoMessage() {}

func (x *SET_GAME_ID) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SET_GAME_ID.ProtoReflect.Descriptor instead.
func (*SET_GAME_ID) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *SET_GAME_ID) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SET_GAME_ID) GetIsReconnect() bool {
	if x != nil {
		return x.IsReconnect
	}
	return false
}

func (x *SET_GAME_ID) GetIsRestore() bool {
	if x != nil {
		return x.IsRestore
	}
	return false
}

func (x *SET_GAME_ID) GetIsBanBootEntity() bool {
	if x != nil {
		return x.IsBanBootEntity
	}
	return false
}

func (x *SET_GAME_ID) GetEntityIdList() []string {
	if x != nil {
		return x.EntityIdList
	}
	return nil
}

type SET_GATE_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateId uint32 `protobuf:"varint,1,opt,name=GateId,proto3" json:"GateId,omitempty"`
}

func (x *SET_GATE_ID) Reset() {
	*x = SET_GATE_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SET_GATE_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SET_GATE_ID) ProtoMessage() {}

func (x *SET_GATE_ID) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SET_GATE_ID.ProtoReflect.Descriptor instead.
func (*SET_GATE_ID) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *SET_GATE_ID) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

type NOTIFY_CREATE_ENTITY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=EntityId,proto3" json:"EntityId,omitempty"`
}

func (x *NOTIFY_CREATE_ENTITY) Reset() {
	*x = NOTIFY_CREATE_ENTITY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NOTIFY_CREATE_ENTITY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NOTIFY_CREATE_ENTITY) ProtoMessage() {}

func (x *NOTIFY_CREATE_ENTITY) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NOTIFY_CREATE_ENTITY.ProtoReflect.Descriptor instead.
func (*NOTIFY_CREATE_ENTITY) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *NOTIFY_CREATE_ENTITY) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type NOTIFY_DESTROY_ENTITY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=EntityId,proto3" json:"EntityId,omitempty"`
}

func (x *NOTIFY_DESTROY_ENTITY) Reset() {
	*x = NOTIFY_DESTROY_ENTITY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NOTIFY_DESTROY_ENTITY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NOTIFY_DESTROY_ENTITY) ProtoMessage() {}

func (x *NOTIFY_DESTROY_ENTITY) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NOTIFY_DESTROY_ENTITY.ProtoReflect.Descriptor instead.
func (*NOTIFY_DESTROY_ENTITY) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *NOTIFY_DESTROY_ENTITY) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type KVREG_REGISTER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrvId string `protobuf:"bytes,1,opt,name=SrvId,proto3" json:"SrvId,omitempty"`
	Info  string `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	Force bool   `protobuf:"varint,3,opt,name=Force,proto3" json:"Force,omitempty"`
}

func (x *KVREG_REGISTER) Reset() {
	*x = KVREG_REGISTER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVREG_REGISTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVREG_REGISTER) ProtoMessage() {}

func (x *KVREG_REGISTER) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVREG_REGISTER.ProtoReflect.Descriptor instead.
func (*KVREG_REGISTER) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *KVREG_REGISTER) GetSrvId() string {
	if x != nil {
		return x.SrvId
	}
	return ""
}

func (x *KVREG_REGISTER) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *KVREG_REGISTER) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CREATE_ENTITY_SOMEWHERE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   uint32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	EntityId string `protobuf:"bytes,2,opt,name=EntityId,proto3" json:"EntityId,omitempty"`
	TypeName string `protobuf:"bytes,3,opt,name=TypeName,proto3" json:"TypeName,omitempty"`
	Data     string `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CREATE_ENTITY_SOMEWHERE) Reset() {
	*x = CREATE_ENTITY_SOMEWHERE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CREATE_ENTITY_SOMEWHERE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CREATE_ENTITY_SOMEWHERE) ProtoMessage() {}

func (x *CREATE_ENTITY_SOMEWHERE) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CREATE_ENTITY_SOMEWHERE.ProtoReflect.Descriptor instead.
func (*CREATE_ENTITY_SOMEWHERE) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *CREATE_ENTITY_SOMEWHERE) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CREATE_ENTITY_SOMEWHERE) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CREATE_ENTITY_SOMEWHERE) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CREATE_ENTITY_SOMEWHERE) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_Message_proto protoreflect.FileDescriptor

var file_Message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x53, 0x45, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x49, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x73, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x49, 0x73, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x49,
	0x73, 0x42, 0x61, 0x6e, 0x42, 0x6f, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x49, 0x73, 0x42, 0x61, 0x6e, 0x42, 0x6f, 0x6f, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x45, 0x54,
	0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x47, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x22, 0x32, 0x0a, 0x14, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54,
	0x45, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x15, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x44,
	0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x0e, 0x4b, 0x56, 0x52,
	0x45, 0x47, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x72, 0x76, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x72, 0x76, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x7d, 0x0a, 0x17, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x4f, 0x4d,
	0x45, 0x57, 0x48, 0x45, 0x52, 0x45, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData = file_Message_proto_rawDesc
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Message_proto_rawDescData)
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Message_proto_goTypes = []interface{}{
	(*SET_GAME_ID)(nil),             // 0: pb.SET_GAME_ID
	(*SET_GATE_ID)(nil),             // 1: pb.SET_GATE_ID
	(*NOTIFY_CREATE_ENTITY)(nil),    // 2: pb.NOTIFY_CREATE_ENTITY
	(*NOTIFY_DESTROY_ENTITY)(nil),   // 3: pb.NOTIFY_DESTROY_ENTITY
	(*KVREG_REGISTER)(nil),          // 4: pb.KVREG_REGISTER
	(*CREATE_ENTITY_SOMEWHERE)(nil), // 5: pb.CREATE_ENTITY_SOMEWHERE
}
var file_Message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SET_GAME_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SET_GATE_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NOTIFY_CREATE_ENTITY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NOTIFY_DESTROY_ENTITY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVREG_REGISTER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CREATE_ENTITY_SOMEWHERE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_rawDesc = nil
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
